version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - scothis
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - scothis
- package-ecosystem: gomod
  directory: "/hack"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - scothis
