version: 2
groups:
  kubernetes:
    patterns:
    - "k8s.io/*"
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - scothis
- package-ecosystem: gomod
  directory: "/"
  groups:
    kubernetes:
      patterns:
      - "k8s.io/*"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - scothis
- package-ecosystem: gomod
  directory: "/hack"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - scothis
